### ISSUE TITLE
Improve icon visibility solution - Remove excessive CSS overrides

### ISSUE THREAD

**Issue by Shiiv664** [Shiiv664/Roleplay_Chat_Frontend#2]
## Problem

Currently, React Icons (react-icons) components like `MdDeleteOutline` and `MdEdit` require extensive CSS overrides to be visible in our message components. We're using very specific CSS with multiple `!important` declarations:

```css
.delete-icon-svg, .edit-icon-svg {
  fill: none !important;
  stroke: #888 !important;
  stroke-width: 2 !important;
  color: #888 !important;
  display: block !important;
  visibility: visible !important;
  opacity: 1 !important;
  width: 16px !important;
  height: 16px !important;
  /* ... many more overrides */
}
```

This approach is:
- **Verbose**: Requires 15+ CSS properties per icon type
- **Hard to maintain**: Need to duplicate this for every new icon
- **Fragile**: Relies heavily on `!important` declarations
- **Not scalable**: Each new icon requires a new CSS class

## Expected Behavior

Icons should be visible by default without requiring extensive CSS overrides. React Icons should work out-of-the-box with minimal styling.

## Investigation Needed

1. **Root cause analysis**: Why are React Icons not visible by default?
   - Is there a conflicting CSS reset/normalize?
   - Are there inherited styles causing issues?
   - Is it related to our component structure or CSS-in-JS approach?

2. **Alternative solutions**:
   - Use a different icon library (Lucide React, Heroicons, etc.)
   - Fix the root CSS issue instead of overriding each icon
   - Use inline SVGs instead of icon components
   - Investigate CSS cascade issues

## Acceptance Criteria

- [ ] Icons are visible without requiring extensive CSS overrides
- [ ] Solution is maintainable and scalable for future icons
- [ ] No need for `!important` declarations
- [ ] Minimal CSS required per icon (ideally just color/size)

## Files Affected

- `src/components/chat/MessageItem.css` (current workaround)
- `src/components/chat/MessageItem.tsx` (icon usage)
- Potentially global CSS files if root cause is found

## Priority

Medium - Current workaround functions but creates technical debt
